name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B license:format clean deploy -P_release_prepare -P_release_sign-artifacts -Pvaadin-install-nodejs -Dmaven.test.skip=true --file pom.xml
